name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd client && npm install

      - name: Run linter
        run: cd client && npm run lint || true

      - name: Build frontend
        run: cd client && npm run build

      # Optional: Deploy to Vercel (automatic if Vercel GitHub integration is enabled)
